### ISSUE TITLE
Error Adding to my own bot

### ISSUE THREAD

**Issue by FreeMyxticss** [ZerioDev/DiscordTickets#2]
I added all ur open source code to my bot and I get a error

On Replit

**Comment by FreeMyxticss** [comment]
**ERROR CODE**


/home/runner/DiscordAIO-1/src/loader.js:13
    client.on(file.split('.')[0], event.bind(null, client));
                                        ^

TypeError: event.bind is not a function
    at Object.<anonymous> (/home/runner/DiscordAIO-1/src/loader.js:13:41)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/DiscordAIO-1/index.js:189:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

**Comment by proudparrot2** [comment]
Hmm. You have NodeJS 16, and DJS 13?

**Comment by 4troDev** [comment]
> I added all ur open source code to my bot and I get a error
> 
> On Replit

Replit wont support NodeJS 16 at the moment but i found something that might help you https://github.com/RLX-OP/node.js-v16-replit
